### ISSUE TITLE
error at step 7

### ISSUE THREAD

**Issue by Kwisss** [PlayVoice/so-vits-svc-5.0#2] opened 2023-04-24 23:26 UTC
preprocess_zzz.py calls vits but preprocess_zzz.py itself is in a map so can't locate it.

if I copy the vits map into prepare it still throws an error at step 7:

 line 252, in __iter__
    ids_bucket = ids_bucket + ids_bucket * (rem // len_bucket) + ids_bucket[:(rem % len_bucket)]
ZeroDivisionError: integer division or modulo by zero in \vits\data_utils.py

is it because vits_pretrain.pt is missing? it does not seem to exist on the internet?

**Comment by MaxMax2016** [comment] 2023-04-25 13:35
the model is still under train, and will be released some days later. the error is caused by the setting of frames [150, 300, 450], after pretrain  model released, i will try to fix bugs.

**Closed** 2023-05-04 02:37 UTC
